server:
  port: 83

spring:
  application:
    name: nacos-order-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'

server-url:
  nacos-user-service: http://nacos-payment-provider